using Figgle;


//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI;
using NStack;
using Terminal.Gui;

// [GenerateFiggleText("ExtravaWall", "standard", "ExtravaWall")]
// [GenerateFiggleText("Version", "nancyj", "     v 0.1")]
// [GenerateFiggleText("ExitSuccess", "smslant", "go play in traffic")]
// [GenerateFiggleText("ExitFail", "thin", "Failed")]
public partial class BannerView {
    public static string ExtravaWall { get; } = FiggleFonts.Standard.Render("ExtravaWall");
    public static string Version { get; } = FiggleFonts.NancyJ.Render("     v 0.1");
    public static string ExitSuccess { get; } = FiggleFonts.SlantSmall.Render("go play in traffic");
    public static string ExitFail { get; } = FiggleFonts.Thin.Render("Failed");
    private readonly int _height;

    new public ustring Text {
        get => bannerText.Text ?? string.Empty;
    }

    public int BannerHeight {
        get => _height;
    }

    public BannerView(BannerType bannerType) {
        InitializeComponent();
        (bannerText.Text, _height) = bannerType switch {
            BannerType.Welcome => ($"\n\n{ExtravaWall}{Version}", 15),
            BannerType.ExitSuccess => ($"\n{ExitSuccess}\n(network traffic)", 9),
            BannerType.ExitFail => ($"\n{ExitFail}\n¯\\_(⊙︿⊙)_/¯\n", 15),
            _ => (string.Empty, 1)
        };
        bannerText.Height = _height;
        Height = _height;

        CanFocus = false;
        bannerText.CanFocus = false;
        AutoSize = false;
        bannerText.AutoSize = false;
        Width = 70;
    }
}
