
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class BannerView : Terminal.Gui.View {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.Label banner;
        
        
        private void InitializeComponent() {
            this.banner = new Terminal.Gui.Label();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = 15;
            this.X = 0;
            this.Y = 0;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.banner.Width = Dim.Fill(0);
            this.banner.Height = 15;
            this.banner.X = 0;
            this.banner.Y = 0;
            this.banner.Data = "banner";
            this.banner.Text = "Banner";
            this.banner.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.banner.CanFocus = false;
            this.Add(this.banner);
            
        }
    }
}
