
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class DisplayProgressBar : Terminal.Gui.View {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        private Terminal.Gui.ColorScheme redOnBlack;

        private ExtravaLabel progressMessage;
        
        private ExtravaProgressBar progressBar;

        private void InitializeComponent() {
            this.progressBar = new ExtravaProgressBar();
            this.progressMessage = new ExtravaLabel();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Magenta);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Magenta);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = 3;
            this.X = 0;
            this.Y = 0;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.progressMessage.Width = Dim.Fill(0);
            this.progressMessage.Height = 1;
            this.progressMessage.X = 0;
            this.progressMessage.Y = 0;
            this.progressMessage.ColorScheme = this.greenOnBlack;
            this.progressMessage.Data = "commandResult";
            this.progressMessage.Text = "Progress";
            this.progressMessage.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.progressMessage);
            this.progressBar.Width = 50;
            this.progressBar.Height = 2;
            this.progressBar.X = 1;
            this.progressBar.Y = Pos.Bottom(progressMessage);
            this.progressBar.Data = "progressBar";
            this.progressBar.Text = "100%";
            this.progressBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.progressBar.Fraction = 1F;
            this.progressBar.BidirectionalMarquee = false;
            this.progressBar.ProgressBarStyle = Terminal.Gui.ProgressBarStyle.Blocks;
            this.progressBar.ProgressBarFormat = Terminal.Gui.ProgressBarFormat.SimplePlusPercentage;
            this.progressBar.SegmentCharacter = '▌';
            this.Add(this.progressBar);
        }
    }
}
