
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class DisplayTextView : Terminal.Gui.View {
        
        private Terminal.Gui.Label textOutput;
        private ColorScheme greenOnBlack;

        private void InitializeComponent() {
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.textOutput = new Terminal.Gui.Label();
            this.Width = 4;
            this.Height = 1;
            this.X = 0;
            this.Y = 0;
            this.textOutput.ColorScheme = this.greenOnBlack;
            this.textOutput.Width = 4;
            this.textOutput.Height = 1;
            this.textOutput.X = 0;
            this.textOutput.Y = 0;
            this.textOutput.Data = "commandResult";
            this.textOutput.Text = "Command Output";
            this.textOutput.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textOutput);
        }
    }
}
