
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class ElevateMenuView : Terminal.Gui.View {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private ExtravaLabel menuTitleLabel;
        
        private Terminal.Gui.ListView listView;
        
        private void InitializeComponent() {
            this.listView = new Terminal.Gui.ListView();
            this.menuTitleLabel = new ExtravaLabel();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = 65;
            this.Height = 5;
            this.X = 0;
            this.Y = 0;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.menuTitleLabel.Width = 65;
            this.menuTitleLabel.Height = 1;
            this.menuTitleLabel.X = 0;
            this.menuTitleLabel.Y = 0;
            this.menuTitleLabel.ColorScheme = this.greenOnBlack;
            this.menuTitleLabel.Data = "menuTitleLabel";
            this.menuTitleLabel.Text = "Would you like to attempt to re-run with elevated permission?";
            this.menuTitleLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.menuTitleLabel);
            this.listView.Width = 40;
            this.listView.Height = 3;
            this.listView.X = 2;
            this.listView.Y = Pos.Bottom(menuTitleLabel) + 1;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Yes: re-run with elevated permission",
                        "No: Quit"});
            this.Add(this.listView);
        }
    }
}
