
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI {
    using NStack;
    using Terminal.Gui;


    public partial class ExitView {

        public void SetHeight(int height) {
            Height = height;
            contentLabel.Height = Height - 6;
        }
        public ExitView(bool isSuccess, ustring title, ustring content) {
            InitializeComponent();
            this.contentLabel.WordWrap = true;
            this.contentLabel.Enabled = false;
            exitButton.Clicked += ExitButton_Clicked;
            if (isSuccess) {
                this.ColorScheme = blackOnGreenCustom;
                this.titleLabel.ColorScheme = greenOnBlackCustom;
            }

            this.titleLabel.Text = title;
            contentLabel.Text = content;
            exitButton.SetFocus();
        }

        private void ExitButton_Clicked() {
            InstallManager.Instance.Exit();
        }
    }
}
