
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI.Components {
    using Terminal.Gui;


    public partial class InstallerView {

        public InstallerView(InstallManager install) {
            InitializeComponent();
            this.wizard.ColorScheme = this.blackOnGreen;
        }
    }
}
