
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class InstallerView : Terminal.Gui.View {
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme blackOnGreen;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.Wizard wizard;
        
        private Terminal.Gui.ProgressBar progressBar;
        
        private void InitializeComponent() {
            this.progressBar = new Terminal.Gui.ProgressBar();
            this.wizard = new Terminal.Gui.Wizard();
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blackOnGreen = new Terminal.Gui.ColorScheme();
            this.blackOnGreen.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Green);
            this.blackOnGreen.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Green);
            this.blackOnGreen.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.BrightGreen);
            this.blackOnGreen.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.BrightGreen);
            this.blackOnGreen.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Green);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.ColorScheme = this.greenOnBlack;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard.Width = Dim.Fill(0);
            this.wizard.Height = Dim.Fill(0);
            this.wizard.X = 0;
            this.wizard.Y = 0;
            this.wizard.Modal = false;
            this.wizard.Data = "wizard";
            this.wizard.Text = "";
            this.wizard.Border.BorderStyle = Terminal.Gui.BorderStyle.Rounded;
            this.wizard.Border.BorderBrush = Terminal.Gui.Color.Green;
            this.wizard.Border.Effect3D = false;
            this.wizard.Border.Effect3DBrush = null;
            this.wizard.Border.DrawMarginFrame = true;
            this.wizard.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard.Title = "Heya";
            this.Add(this.wizard);
            this.progressBar.Width = Dim.Percent(45f);
            this.progressBar.Height = 2;
            this.progressBar.X = Pos.Center();
            this.progressBar.Y = Pos.AnchorEnd(1);
            this.progressBar.ColorScheme = this.redOnBlack;
            this.progressBar.Data = "progressBar";
            this.progressBar.Text = "100%";
            this.progressBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.progressBar.Fraction = 1F;
            this.progressBar.BidirectionalMarquee = true;
            this.progressBar.ProgressBarStyle = Terminal.Gui.ProgressBarStyle.Continuous;
            this.progressBar.ProgressBarFormat = Terminal.Gui.ProgressBarFormat.SimplePlusPercentage;
            this.progressBar.SegmentCharacter = '█';
            this.wizard.Add(this.progressBar);
        }
    }
}
