
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI
{
    using System.Diagnostics;
    using ExtravaWallSetup.GUI.Framework;
    using Terminal.Gui;


    public partial class StartMenuView {
        bool _pendingClick;
        private InstallManager _installManager;

        public StartMenuView(InstallManager installManager) {
            _installManager = installManager;
            InitializeComponent();
            this.listView.MouseClick += ListView_MouseClick;
            this.listView.KeyPress += ListView_KeyPress;
            this.DrawContentComplete += StartMenuView_DrawContentCompleteAsync;
            this.listView.SetFocus();
        }

        private async void StartMenuView_DrawContentCompleteAsync(Rect obj) {
            var shouldRun = _pendingClick;
            _pendingClick = false;
            if (shouldRun) {
                await Run(this.listView.SelectedItem);
            }
        }

        private void ListView_KeyPress(KeyEventEventArgs args) {
            if (args.KeyEvent.Key == Key.Enter) {
                _pendingClick = true;
            }
        }

        private void ListView_MouseClick(MouseEventArgs args) {
            _pendingClick = true;
        }

        private async Task Run(int selectedItem) {
            switch (selectedItem) {
                case 0:
                    await _installManager.InstallAsync();
                    break;
                case 1:
                    await _installManager.RecoverAsync();
                    break;
                case 2:
                    _installManager.Exit();
                    break;

            }
        }
    }
}
