using Figgle;
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI {
    using Terminal.Gui;

    [GenerateFiggleText("ExtravaWall", "standard", "ExtravaWall")]
    [GenerateFiggleText("Version", "nancyj", "     v 0.1")]
    public partial class BannerView {
        
        public BannerView() {
            InitializeComponent();
            banner.Text = ExtravaWall + Version;
          
            CanFocus = false;
            banner.CanFocus = false;
            AutoSize = false;
            banner.AutoSize = false;
            Width = 60;
            Height = 15;
        }
    }
}
