
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI {
    using Terminal.Gui;
    
    
    public partial class StartMenuView {
        
        public StartMenuView() {
            InitializeComponent();
           
        }
    }
}
