
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.22.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ExtravaWallSetup.GUI.Components {
    using System;
    using Terminal.Gui;


    public partial class CommandView : Terminal.Gui.View {

        private ExtravaLabel commandResult;

        private void InitializeComponent() {
            this.commandResult = new ExtravaLabel();
            this.Width = 4;
            this.Height = 1;
            this.X = 0;
            this.Y = 0;
            this.commandResult.Width = 4;
            this.commandResult.Height = 1;
            this.commandResult.X = 0;
            this.commandResult.Y = 0;
            this.commandResult.Data = "commandResult";
            this.commandResult.Text = "Command Output";
            this.commandResult.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.commandResult);
        }
    }
}
