
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ExtravaCore.Generators;
internal static class Log {
    public static List<string> Logs { get; } = new();
    private static int logFlushCounter = 0;
    public static string header = """
    // <auto-generated />
    #nullable enable

    """;
    public static void Print(string msg) => Logs.Add($"//\t{DateTime.Now.ToString("MM-dd-yyy\tHH:mm:ss.ffffff")}\t{msg}");

    // More print methods ...

    public static void FlushLogs(SourceProductionContext context) {
        logFlushCounter++;
        context.AddSource($"logs{logFlushCounter}.g.cs", SourceText.From(header + string.Join("\n", Logs), Encoding.UTF8));
        Logs.Clear();
    }

    public static void FlushLogs(IncrementalGeneratorPostInitializationContext context) {
        logFlushCounter++;
        context.AddSource($"logs{logFlushCounter}.g.cs", SourceText.From(header + string.Join("\n", Logs), Encoding.UTF8));
        Logs.Clear();
    }
}